[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "frankenphp run --config /app/Caddyfile"
healthcheckPath = "/up"
healthcheckTimeout = 120
healthcheckInterval = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
