[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/usr/local/bin/docker-entrypoint.sh frankenphp run --config /app/Caddyfile"
healthcheckPath = "/up"
healthcheckTimeout = 180
healthcheckInterval = 10
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
